name: Greenlights

on:
  schedule:
    - cron: '37 5 * * *'
  workflow_dispatch:

jobs:
  greenlights:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configurar git con credenciales propias
        run: |
          git config user.name "Julio Reyes"
          git config user.email "juliojesusreyes@gmail.com"

      - name: greenlights
        run: |
          if [ "$(date +%u)" -eq 1 ]; then
            echo "# Week of $(date +%F)" > .upflow.txt
            git add .upflow.txt
            git commit -m "New Greenlights 🌱 - $(date +%F)"
          fi

          COMMITS=$(( ( RANDOM % 5 )  + 1 ))
          for i in $(seq 1 $COMMITS); do
            echo "GreenLight $i - $(date)" >> .upflow.txt
            git add .upflow.txt
            git commit -m "GreenLight $i - $(date +%F_%T)"
          done

      - name: Pushing changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
